version: '3.5'

services:
  php:
    build: ./.misc/docker/php
    volumes:
    - .:/app
  nginx:
    image: nginx:alpine
    volumes:
    - ./public:/app/public
    - ./.misc/docker/nginx:/etc/nginx/conf.d
    ports:
    - 8000:80
  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    - ./.misc/docker/mysql-schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
    - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
    - 8001:80

volumes:
  mysql_data:
