version: '3.3'

services:
  app:
    build:
      context: .
      args:
      - TARGET=dev
    volumes:
    - .:/app:rw
    ports:
    - 0.0.0.0:8000:80/tcp
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: s3cret
      MYSQL_DATABASE: project
    volumes:
    - database_data:/var/lib/mysql:rw
    - ./_misc/docker/database/schema:/docker-entrypoint-initdb.d:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: s3cret
      UPLOAD_LIMIT: 2048M
      PMA_USER_CONFIG_BASE64: PD9waHAKJGNmZ1snVGVtcERpciddID0gJy90bXAnOw==
    ports:
    - 127.0.0.1:8001:80/tcp
    logging:
      driver: none

volumes:
  database_data:
