version: '3.7'

services:
  php:
    build: ./.misc/docker/php
    volumes: [.:/app]
  web:
    build: ./.misc/docker/web
    volumes:
    - ./public:/app/php
    - phpmyadmin-files:/app/phpmyadmin
    ports: [8000-8001:8000-8001]
  database:
    build: ./.misc/docker/database
    volumes:
    - database-data:/var/lib/mysql
    - ./.misc/docker/database/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
  phpmyadmin:
    build: ./.misc/docker/phpmyadmin
    volumes: [phpmyadmin-files:/var/www/html]

volumes:
  database-data:
  phpmyadmin-files:
